import type { Metadata } from "next";
import "./globals.css";
import { getSession } from "./lib/session.server";
import Link from "next/link";
import { Jersey_10 } from 'next/font/google'
const jersey = Jersey_10({ weight: "400" });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession();
  return (
    <html lang="en">
      <body className="bg-base-100 h-100dvh pb-10 min-h-dvh">
        <div className="navbar bg-base-100 shadow-sm">
          <div className="flex-1">
            <Link href="/" className={`btn btn-ghost ${jersey.className} text-xl`}>GRIDGO</Link>
          </div>
          <div className="flex-none z-10">
            {session ? (
              <ul className="menu">
                <li>
                  <details>
                    <summary>
                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none"
                        stroke="currentColor" strokeWidth="2" className="lucide-menu">
                        <path d="M4 12h16" /><path d="M4 18h16" /><path d="M4 6h16" />
                      </svg>
                    </summary>
                    <ul className="bg-base-100 rounded-t-none p-2 absolute right-0 w-xs">
                      <li><a href="/friends">Friends</a></li>
                      <li><a href="/my-cards">My Cards</a></li>
                      <li><a>Settings</a></li>
                      <li><a href="/logout">Log Out</a></li>
                    </ul>
                  </details>
                </li>
              </ul>
            ) : (
              <Link href="/login" className="btn btn-primary">LOGIN</Link>
            )}
          </div>
        </div>
        {!session && <h1 className="alert alert-warning alert-outline">Welcome to GridGO!, get started by making an account or logging in!</h1>}
        {session && <a className="btn btn-primary btn-xl btn-circle fixed bottom-0 right-0 m-10 z-50" href="/create">+</a>}
        {session && <h1 className="alert alert-info alert-outline">Welcome to GridGO!, get started by making some cards!</h1>}
        {children}
      </body>
    </html >
  );
}
